version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/vhost:/etc/nginx/vhost.d
      - ./volumes/conf:/etc/nginx/conf.d
      - ./volumes/html:/usr/share/nginx/html
      - ./volumes/dhparam:/etc/nginx/dhparam
      - ./volumes/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - ./volumes/certs:/etc/nginx/cers:rw
      - ./volumes/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    name: nginx-proxy

